# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07d5f9c5e89d67f5ca89ae2514e3a053f6793117a2597db47358db0b86d21146e3b554a629151952501c279e8cd1c38ee0a408f9e2a0b94741f4c84d7c598672

test:
  secret_key_base: 1dd6aa4b99a3858c61e3bf44a5a0db1b06073d0fefdcaca9709063f2a6e0e1054afe1a010a9928e133742ec9902a08e12838bdb4ca63040e2cd8e5cf1023651f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
